1.0.0 Release

diff --git a/s3d-aws-ec2-get-name-tag b/s3d-aws-ec2-get-name-tag
--- a/s3d-aws-ec2-get-name-tag
+++ b/s3d-aws-ec2-get-name-tag
@@ -1,11 +1,11 @@
 #!/bin/bash
-
 set -e
 
-n=1; p="$1"; inst="$p"; [ -n "$p" ] || err="\$$n <instance-id> is required"
+n=1; p="$1"; inst="$p"; [ -n "$p" ] \
+  || err="\$$n <instance-id> is required"
 
-[ -z "$err" ] || { 
-  { 
+[ -z "$err" ] || {
+  {
     echo -e "ERR..: $err"
     echo -e "USE..: $(echo "$0" | sed 's/.*\///') <instance-id>"
     echo -e "ABOUT: Gets the EC2 instance's \"Name\" tag."
@@ -16,7 +16,7 @@ n=1; p="$1"; inst="$p"; [ -n "$p" ] || err="\$$n <instance-id> is required"
 # get running instances
 aws ec2 describe-instances | jq -r '
 .Reservations[].Instances[]
-| select(.InstanceId == "'"$inst"'") 
+| select(.InstanceId == "'"$inst"'")
 | .Tags[]
 | select(.Key == "Name")
 | .Value
