0.1.8 Shellcheck limit fixes

diff --git a/s3d-flow-finish b/s3d-flow-finish
--- a/s3d-flow-finish
+++ b/s3d-flow-finish
@@ -1,7 +1,9 @@
 #!/bin/bash
+# shellcheck disable=SC1091
+# shellcheck disable=SC2001
 set -e
 
-n=1; p="$1"; name="$p";  [ -n "$p" ] || err="\$$n (message) is required"
+n=1; p="$1"; message="$p";  [ -n "$p" ] || err="\$$n (message) is required"
 
 [ -z "$err" ] || { {
   echo -e "ERR..: $err"
@@ -13,20 +15,23 @@ export S3D_FLOW_FINISHING=true
 
 if [ -e ./s3d-finish ]; then
   ./s3d-finish
+  exit
 fi
 
-s3d-flow-check
+if ! s3d-flow-check; then
+  echo -e 'FLOW: check failed'
+fi
 
 v=$(s3d-flow-json | jq -r .latest)
 v2=$(s3d-flow-json | jq -r .release)
 if [[ "$v" == "$v2" ]]; then
   echo "FLOW: ALREADY FINISHED $S3D_MODULE?ref=$(git describe)"
 else
-  v_=$(echo $v | sed 's/\./\\\./')
-  v2_=$(echo $v2 | sed 's/\./\\\./')
+  v_=$(echo "$v" | sed 's/\./\\\./')
+  v2_=$(echo "$v2" | sed 's/\./\\\./')
   sed -i -e 's/\['"$v_"'\]/\['"$v2_"'\]/' CHANGES.md
   s3d-flow-reset
-  . s3d-flow "$1"
+  . s3d-flow "$message"
 fi
 
 echo "FLOW: FINISHED $S3D_MODULE?ref=$(git describe)"
